### ISSUE TITLE
notes given as MIDI values only

### ISSUE THREAD

**Issue by allorens** [johentsch/ms3#7]
When extracting the notes, it would be useful to have their names besides the midi indices, the same as the ambitus is referred to through midi indices and note names.

**Comment by johentsch** [comment]
In fact, notes are given as scale degrees. I will add options to select other representations, just as in the mozart_loader...

**Comment by chfin** [comment]
Maybe this could be integrated with [pitchtypes](https://github.com/DCMLab/pitchtypes), either by providing octaves in addition to fifths (=tpc) or by already providing the full pitch name in the pitchtypes notation format. The latter is more readable but the former wouldn't require parsing for reusing it with pitchtypes.

It's a bit subtle though because there are two possible fifths/octaves representations. One is independent (fifths encode note name, octaves encode absolute octave, D4 = (2,4)), the other is dependent (fifths and octaves together encode the distance from C4, so D4 = (2,-1), two fifths up, one octave down. The independent version is intuitively more readable (because both values have independent meaning) but the dependent version is much easier to calculate with and is therefore used in the pitchtypes library.
