### ISSUE TITLE
Unclear distinction between grace notes and appoggiaturas

### ISSUE THREAD

**Issue by allorens** [johentsch/ms3#8]
ms3 seems to distinguish between grace notes and appogiaturas depending on their duration, although this is not always accurate from a musicological point of view. 

In the example:
- the C semiquaver in b. 1 and the D crotchet in b.3 in the voice are treated as grace notes (grace16 & grace4 respectively)
- the D and B quavers in the violins in b. 3 are retrieved as appoggiature.
![image](https://user-images.githubusercontent.com/61057980/96006099-6b3ebe00-0e3d-11eb-92ac-c3d45896bf15.png)

This file comes from a previous XML, but the same happens when the music is engraved in MuseScore directly (different notes but same durations).

**Comment by johentsch** [comment]
This is nothing that MS3 can control, as it simply reproduces the values from the source code.

**Comment by allorens** [comment]
Just speaking out loud: Couldn't the distinction be made by taking into account the duration of the real note and the proportion established between it at the grace note/appogiatura?

**Comment by johentsch** [comment]
I wouldn't feel comfortable doing that because the value merely represents particular notations which might be used with different meanings, as you have noted, so I am not confident that an automatic distinction would hold for any repertoire. Rather, I think this distinction should be made within the individual project.
________________________________
